import AppLayout from "@layouts/AppLayout";
import React from "react";
import { Element } from "react-scroll";
import GridLayout from "src/containers/GridLayout";

function PrivacyPolicy() {
  const tabs = [
    "Definitions and Key Terms",
    "What Information Do We Collect? ",
    "How Do We Use The Information We Collect?",
    "When do we use customer information from third parties?",
    "Do we share the information we collect with third parties?",
    "Where and when is information collected from customers?",
    "How Do We Use Your Email Address?",
    "Could my information be  transferred to other countries?",
    "Is the information collected through our service secure?",
    "Can I update or correct my information?",
    "How Long Do We Keep Your Information?",
    "How Do We Protect Your Information?",
    "Governing Law",
    "Your Consent",
    "Links to Other websites",
    "Cookies",
    "Remarketing Services",
    "Kids' Privacy",
    "Changes To Our  Privacy Policy",
    "Third-Party Services",
    "Tracking Technologies",
    "Information about General Data Protection Regulation (GDPR)",
    "What is GDPR?",
    "What is personal data?",
    "Why is GDPR important?",
    "Individual Data",
  ];

  return (
    <AppLayout>
      <GridLayout heading="Privacy Policy" tabs={tabs}>
        <section>
          <p className="text-t14 lg:text-[1rem] font-product_sans text-black/80 leading-[1.5rem]">
            Niteon (&quot;we&quot;, &quot;our&quot;, or &quot;us&quot;) is
            committed to protecting your privacy. This Privacy Policy explains
            how your personal Information is collected, used, and disclosed by
            Niteon This Privacy Policy applies to our website,{" "}
            <a href="https://www.niteon.co" className="text-blue-600 underline">
              www.niteon.co
            </a>
            , and its associated subdomains (collectively, our
            &quot;Service&quot;). By accessing or using our Service, you signify
            that you have read, understood, and agree to our collection,
            storage, use, and disclosure of your personal information as
            described in this Privacy Policy and our Terms of Service.
          </p>
        </section>
        <section>
          <Element className={"block"} name="0">
            <h2 className="font-roboto mb-[1.25rem] font-semibold text-t18 lg:text-t24 text-black first-letter:capitalize">
              Definitions and key Terms
            </h2>
            <div className="space-y-[1.5rem]">
              {[
                "To help explain things as clearly as possible in this Privacy Policy. every time any of these terms are referenced, are strictly defined as:",
                `• Cookie: small amount of data generated by a website and saved
                by your web browser. It is used to identify your browser,
                provide analytics, remember Information about you such as your
                language preference or login information.`,
                `• Company: when this policy mentions "Company", "we", "us," or "our," it refers to Niteon LLC, 1942, Broadway street, Boulder, Colorado United States that is responsible for your information under this Privacy Policy. 
                `,
                `• Country: where Niteon or the owners/founders of Niteon are based, in this case is United States.`,
                `• Customer: refers to the company, organization or person that signs up to use the relationships with your consumers or service users.`,
                `• Device: any Internet connected device such as a phone, tablet, computer or any other device that can be used to visit Niteon and use the services.`,
                `• IP address: Every device connected to the Internet is assigned a number known as an Internet protocol (IP) address. These numbers are usually assigned in geographic blocks. An IP address can often be used to identify the location from to the internet Personnel: refers to those individuals who are employed by Niteon or are under contract to perform a service on behalf of one of the parties.`,
                `• Personal Data: any information that directly. indirectly, or in connection with other information- Including a personal identification number - allows for the identification or identifiability of a natural person.`,
                `•  Service: refers to the service provided by Niteon as described in the relative terms (if available) and on this platform. `,
                `• Third-party service: refers to advertisers, contest sponsors, promotional and marketing partners, and others who provide our content or whose products or services we think may interest you.`,
              ].map((p, index) => (
                <p
                  key={index}
                  className="text-t14 lg:text-[1rem] font-product_sans text-black/80 leading-[1.5rem]"
                >
                  {p}
                </p>
              ))}
              <p className="text-t14 lg:text-[1rem] font-product_sans text-black/80 leading-[1.5rem]">
                • Website: Niteon&apos;s site, which can be accessed via this
                URL:{" "}
                <a
                  href="https://www.niteon.co"
                  className="text-blue-600 underline"
                >
                  www.niteon.co
                </a>
              </p>
              <p className="text-t14 lg:text-[1rem] font-product_sans text-black/80 leading-[1.5rem]">
                • You: a person or entity that is registered with Niteon to use
                the Services.
              </p>
            </div>
          </Element>
        </section>
        <section>
          <Element className={"block"} name="1">
            <h2 className="font-roboto mb-[1.25rem] font-semibold text-t18 lg:text-t24 text-black first-letter:capitalize">
              What Information Do We Collect?
            </h2>
            <div className="space-y-[1.5rem]">
              {[
                "We collect information from you when you visit our service, register, place an order, subscribe to our newsletter, respond to a survey or fill out a form",
                `• Name / Username`,
                `• Phone Numbers`,
                `• Email Addresses`,
                `• Mailing Addresses`,
                `• Job Titles`,
                `• Billing Addresses`,
                `• Debit/credit card numbers`,
                `• Age`,
                `We also collect information from mobile devices for a better user experience, although these features are completely optional: `,
                `• Location (GPS): Location data Location data helps to create an accurate representation of your Interests, and this can be used to bring more targeted and relevant ads to potential customers.`,
                `• PhoneBook (Contacts list):service to be much more easy to use by the user, since accessing your contacts from the app makes you save tons of time.`,
              ].map((p, index) => (
                <p
                  key={index}
                  className="text-t14 lg:text-[1rem] font-product_sans text-black/80 leading-[1.5rem]"
                >
                  {p}
                </p>
              ))}
            </div>
          </Element>
        </section>
        <section>
          <Element className={"block"} name="2">
            <h2 className="font-roboto mb-[1.25rem] font-semibold text-t18 lg:text-t24 text-black first-letter:capitalize">
              How Do We Use The Information We Collect?
            </h2>
            <div className="space-y-[1.5rem]">
              {[
                "Any of the information we collect from you may be used in one of the following ways:",
                `• To personalize your experience (your information helps us to better respond to your individual needs)`,
                `• To improve our service (we continually strive to improve our service offerings based on the information and feedback we receive from you)`,
                `• To improve customer service (your information helps us to more effectively respond to your customer service requests and support needs) `,
                `• To process transactions`,
                `• To administer a contest, promotion, survey or other site feature`,
                `• To send periodic emails`,
              ].map((p, index) => (
                <p
                  key={index}
                  className="text-t14 lg:text-[1rem] font-product_sans text-black/80 leading-[1.5rem]"
                >
                  {p}
                </p>
              ))}
            </div>
          </Element>
        </section>
        <section>
          <Element className={"block"} name="3">
            <h2 className="font-roboto mb-[1.25rem] font-semibold text-t18 lg:text-t24 text-black first-letter:capitalize">
              When do we use customer information from third parties?
            </h2>

            <p className="text-t14 lg:text-[1rem] font-product_sans text-black/80 leading-[1.5rem]">
              We receive some information from the third parties when you
              contact us. For example, when you submit your email address to us
              to show Interest in becoming our customer, we receive information
              from a third party that provides automated fraud detection
              services to us. We also occasionally collect Information that is
              made publicly available on social media websites. You can control
              how much of your information social media websites make public by
              visiting those websites and changing your privacy settings
            </p>
          </Element>
        </section>
        <section>
          <Element className={"block"} name="4">
            <h2 className="font-roboto mb-[1.25rem] font-semibold text-t18 lg:text-t24 text-black first-letter:capitalize">
              Do we share the information we collect with third parties?
            </h2>

            <div className="space-y-[1.5rem]">
              {[
                `We may share the information that we collect, both personal and non- personal, with third parties such as advertisers, contest sponsors, promotional and marketing partners, and others who provide our content or whose products or services we think may interest you current and future affiliated companies and business partners. and if we are involved in a merger, asset sale or other business reorganization, we may also share or transfer your personal and non- personal information to our successors-in-interest.`,
                `We may engage trusted third party service providers to perform functions and provide services to us, such as hosting and maintaining our servers and our service, database storage and management, e-mail management, storage marketing, credit card processing, customer service and fulfilling orders for products and services you may purchase through our service. We will likely share your personal information, and possibly some non-personal information, with these third parties to enable them to perform these services for us and for you.`,
                `We may share portions of our log file data, including IP addresses, for analytics purposes with third parties such as web analytics partners, application developers, and ad networks. If your IP address is shared, it may be used to estimate general location and other technographics such as connection speed, whether you have visited the service in a shared location, and type of device used to visit the service. They may aggregate information about our advertising and what you see on the service and then provide auditing, research and reporting for us and our advertisers.`,
                `We may also disclose personal and non-personal information about you to government or law enforcement officials or private parties as we, in our sole discretion, believe necessary or annmariste in verder to reenant to claims, legal process (including subpoenas), to protect our rights and interests or those of a third party, the safety of the public or any person, to prevent or stop any illegal, unethical, or legally actionable activity, ar to otherwise comply with applicable court orders, laws, rules and regulations.`,
              ].map((p, index) => (
                <p
                  key={index}
                  className="text-t14 lg:text-[1rem] font-product_sans text-black/80 leading-[1.5rem]"
                >
                  {p}
                </p>
              ))}
            </div>
          </Element>
        </section>
        <section>
          <Element className={"block"} name="5">
            <h2 className="font-roboto mb-[1.25rem] font-semibold text-t18 lg:text-t24 text-black first-letter:capitalize">
              Where and when is information collected from customers?
            </h2>

            <p className="text-t14 lg:text-[1rem] font-product_sans text-black/80 leading-[1.5rem]">
              We will collect personal Information that you submit to us. We may
              also receive personal Information about you from third parties as
              described above.
            </p>
          </Element>
        </section>
        <section>
          <Element className={"block"} name="6">
            <h2 className="font-roboto mb-[1.25rem] font-semibold text-t18 lg:text-t24 text-black first-letter:capitalize">
              How Do We Use Your Email Address?
            </h2>

            <div className="space-y-[1.5rem]">
              {[
                `By submitting your email address on our service, you agree to receive emails from us. You can cancel your participation in any of these email lists at any time by clicking on the opt-out link or other unsubscribe option that is included in the respective email. We only send emails to people who have authorized us to contact them, either directly, or through a third party. We do not send unsolicited commercial emails, because we hate spam as much as you do. By submitting your email address, you also agree to allow us to use your email address for customer audience targeting on sites like Facebook, where we display custom advertising to specific people who have opted-in to receive communications from us.`,
                `Email addresses submitted only through the order processing page will be used for the sole purpose of sending you information and updates pertaining to your order. If, however, you have provided the same email to us through another method, we may use it for any of the purposes stated in this Policy. Note: If at any time you would like to unsubscribe from receiving future emails, we include detailed unsubscribe instructions at the bottom of each email.`,
              ].map((p, index) => (
                <p
                  key={index}
                  className="text-t14 lg:text-[1rem] font-product_sans text-black/80 leading-[1.5rem]"
                >
                  {p}
                </p>
              ))}
            </div>
          </Element>
        </section>
        <section>
          <Element className={"block"} name="7">
            <h2 className="font-roboto mb-[1.25rem] font-semibold text-t18 lg:text-t24 text-black first-letter:capitalize">
              Could my information be transferred to other countries?
            </h2>

            <p className="text-t14 lg:text-[1rem] font-product_sans text-black/80 leading-[1.5rem]">
              We are incorporated in United States and Nigeria. Information
              collected via our website, through direct interactions with you,
              or from use of our help services may be transferred from time to
              time to our offices or personnel, or to third parties, located
              throughout the world, and may be viewed and hosted anywhere in the
              world, Including countries that may not have laws of general
              applicability regulating the use and transfer of such data. To the
              fullest extent allowed by applicable law, by using any of the
              above you voluntarily co Maximum 10 screenshots transfer and
              hosting of such information.
            </p>
          </Element>
        </section>
        <section>
          <Element className={"block"} name="8">
            <h2 className="font-roboto mb-[1.25rem] font-semibold text-t18 lg:text-t24 text-black first-letter:capitalize">
              Is the information collected through our service secure?
            </h2>

            <p className="text-t14 lg:text-[1rem] font-product_sans text-black/80 leading-[1.5rem]">
              We take precautions to protect the security of your information.
              We have physical, electronic, and managerial procedures to help
              safeguard, prevent unauthorized access, maintain data security,
              and correctly use your information, However, neither people nor
              Including encryption systems. In addition, people can commit
              Intentional crimes, make mistakes or fail to follow policies.
              Therefore, while we use reasonable efforts to protect your
              personal information, we cannot guarantee its absolute security.
              If applicable law imposes any non-disclaimable duty to protect
              your personal information, you agree that intentional misconduct
              will be the standards. used to measure our compliance with that
              duty.
            </p>
          </Element>
        </section>
        <section>
          <Element className={"block"} name="9">
            <h2 className="font-roboto mb-[1.25rem] font-semibold text-t18 lg:text-t24 text-black first-letter:capitalize">
              Can I update or correct my information?
            </h2>
            <div className="space-y-[1.5rem]">
              {[
                `The rights you have to request updates or corrections to the Information we collect depend on your relationship with us.`,
                `Personnel may update or correct their information as detailed in our internal company employment policies. Customers have the right to request the restriction of certain uses and disclosures of personally Identifiable Information as follows You can contact us in order to (1) update or correct your personally Identifiable information, (2) change your preferences with respect to communications and other Information you receive from us, or (3) delete the personally identifiable information maintained about you on our systems (subject to the following paragraph), by cancelling your account. Such updates, corrections, changes and deletions will have no effect on other information that we maintain, or information that we have provided to third parties in accordance with this Privacy Policy prior to such update, correction, change or deletion. To protect your privacy and security, we may take reasonable steps (such as requesting a unique password) to verify your identity before granting you profile access or making corrections. You are responsible for maintaining the secrecy of your unique password and account Information at all times. You should be aware that it is not technologically possible to remove each and every record of the Information you have provided to us from our system. The need to back up our systems to protect information from inadvertent loss means that a copy of your Information may exist in a non-erasable form that will be difficult or inescible for us to promptly after receiving your request, all personal information stored in databases we actively use, and other readily searchable media will be updated, corrected, changed or deleted, as appropriate as soon as and to the extent reasonably and technically practicable. If you are an end user and wish to update, delete, or receive any information we have about you, you may do so by contacting the organization of which you are a customer.`,
                `• Personnel:`,
                `If you are one of our workers or applicants, we collect information you voluntarily provide to us. We use the information collected for Human Resources purposes in order to administer benefits to workers and screen applicants. You may contact us in order to (1) update or correct your information, (2) change your preferences with respect to communications and other information you receive from us, or (3) receive a record of the information we have relating to you. Such updates, corrections, changes and deletions will have no effect on other information that we have provided to third parties in accordance with this Privacy Policy prior to such update, correction, change or deletion`,
                `• Sale of Business:`,
                `We reserve the right to transfer Information to a third party in the event of a sale, merger or other transfer of all or substantially all of the assets of us or any of its Corporate Affiliates (as defined herein), or that portion of us or any of its Corporate Affiliates to which the Service relates, or in the event that we discontinue our business or file a petition or have filed against us a petition in bankruptcy, reorganization or similar proceeding, provided that the third party agrees to adhere to the terms of this Privacy Policy.
                `,
                `• Affiliates: `,
                `We may disclose information (including personal information) about you to our Corporate Affiliates. For purposes of this Privacy Policy, "Corporate Affiliate" means any person or entity which directly or indirectly controls, is controlled by or is under common control with us, whether by ownership or otherwise. Any information relating to you that we provide to our Corporate Affiliates will be treated by those Corporate Affiliates in accordance with the terms of this Privacy Policy.`,
              ].map((p, index) => (
                <p
                  key={index}
                  className="text-t14 lg:text-[1rem] font-product_sans text-black/80 leading-[1.5rem]"
                >
                  {p}
                </p>
              ))}
            </div>
          </Element>
        </section>
        <section>
          <Element className={"block"} name="10">
            <h2 className="font-roboto mb-[1.25rem] font-semibold text-t18 lg:text-t24 text-black first-letter:capitalize">
              How Long Do We Keep Your Information?
            </h2>

            <p className="text-t14 lg:text-[1rem] font-product_sans text-black/80 leading-[1.5rem]">
              We keep your information only so long as we need it to provide
              service to you and fulfill the purposes described in this policy.
              This is also the case for anyone that we share your information
              with and who carries out services on our behalf. When we no longer
              need to use your information and there is no need for us to keep
              it to comply with our legal or regulatory obligations, we&apos;ll
              either remove it from our systems or depersonalize It so that we
              can&apos;t identify you.
            </p>
          </Element>
        </section>
        <section>
          <Element className={"block"} name="11">
            <h2 className="font-roboto mb-[1.25rem] font-semibold text-t18 lg:text-t24 text-black first-letter:capitalize">
              How Do We Protect Your Information?
            </h2>

            <p className="text-t14 lg:text-[1rem] font-product_sans text-black/80 leading-[1.5rem]">
              We implement a variety of security measures to maintain the safety
              of your personal information when you place an order or enter,
              submit, or access your personal Information. We offer the use of a
              secure server. All supplied sensitive/credit information is
              transmitted via Secure Socket Layer (SSL) technology and then
              encrypted into our Payment gateway providers database only to be
              accessible by those authorized with special access rights to such
              systems, and are confidential. After a transaction, your private
              information (credit cards, social security numbers, financial,
              etc.) is never kept on file. We cannot, however, ensure or warrant
              the absolute security of any information you transmit to us or
              guarantee that your information on the Service may not be
              accessed, disclosed, altered, or destroyed by a breach of any of
              our physical, technical, or managerial safeguards
            </p>
          </Element>
        </section>
        <section>
          <Element className={"block"} name="12">
            <h2 className="font-roboto mb-[1.25rem] font-semibold text-t18 lg:text-t24 text-black first-letter:capitalize">
              Governing Law
            </h2>

            <p className="text-t14 lg:text-[1rem] font-product_sans text-black/80 leading-[1.5rem]">
              In laws of United States, excluding its conflicts of law rules,
              shall govern this Agreement and your use of our service. Your use
              of our service may also be subject to other local, state,
              national, or International laws.
            </p>
          </Element>
        </section>
        <section>
          <Element className={"block"} name="13">
            <h2 className="font-roboto mb-[1.25rem] font-semibold text-t18 lg:text-t24 text-black first-letter:capitalize">
              Your Consent
            </h2>

            <p className="text-t14 lg:text-[1rem] font-product_sans text-black/80 leading-[1.5rem]">
              By using our service, registering an account, or making a
              purchase, you consent to this Privacy Policy.
            </p>
          </Element>
        </section>
        <section>
          <Element className={"block"} name="14">
            <h2 className="font-roboto mb-[1.25rem] font-semibold text-t18 lg:text-t24 text-black first-letter:capitalize">
              Links to Other websites
            </h2>

            <p className="text-t14 lg:text-[1rem] font-product_sans text-black/80 leading-[1.5rem]">
              This Privacy Policy applies only to the Services The Services may
              contain links to other websites not operated or controlled by us.
              We are not responsible for the content, accuracy or opinions
              expressed in such websites, and such websites are not
              investigated, monitored or checked for accuracy or completeness by
              us. Please remember that when you use a link to go from the
              Services to another website, our Privacy Policy is no longer in
              effect. Your browsing and Interaction on any other website,
              Including those that have a link on website&apos;s own rules and
              policies. Such third parties may use their own cookies or other
              methods to collect information about you.
            </p>
          </Element>
        </section>
        <section>
          <Element className={"block"} name="15">
            <h2 className="font-roboto mb-[1.25rem] font-semibold text-t18 lg:text-t24 text-black first-letter:capitalize">
              Cookies
            </h2>

            <p className="text-t14 lg:text-[1rem] font-product_sans text-black/80 leading-[1.5rem]">
              We use &quot;Cookies&quot; to identify the areas of our website
              that you have visited. A Cookie is a small piece of data stored on
              your computer or mobile device by your web browser. We use Cookies
              to personalize the Content that you see on our website. Most web
              browsers can be set to disable the use Cones, However, you disable
              Cookies, you may not be able to access functionality on our
              website correctly or at all. We never place Personally
              Identifiable Information in Cookies.
            </p>
          </Element>
        </section>
        <section>
          <Element className={"block"} name="16">
            <h2 className="font-roboto mb-[1.25rem] font-semibold text-t18 lg:text-t24 text-black first-letter:capitalize">
              Remarketing Services
            </h2>

            <p className="text-t14 lg:text-[1rem] font-product_sans text-black/80 leading-[1.5rem]">
              We use remarketing services. What Is Remarketing? In digital
              marketing, remarketing (or retargeting) is the practice of serving
              ads across the internet to people who have already visited your
              website. It allows your company to seem like they&apos;re
              &quot;following&quot; people around the internet by serving ads on
              the websites and platforms they use most Payment Details In
              respect to any credit card or other payment processing details you
              have provided us, we commit that this confidential information
              will be stored in the most secure manner possible.
            </p>
          </Element>
        </section>
        <section>
          <Element className={"block"} name="17">
            <h2 className="font-roboto mb-[1.25rem] font-semibold text-t18 lg:text-t24 text-black first-letter:capitalize">
              Kids&apos; Privacy
            </h2>

            <p className="text-t14 lg:text-[1rem] font-product_sans text-black/80 leading-[1.5rem]">
              We collect information from kids under the age of 13 just to
              better our services. If You are a parent or guardian and You are
              aware that Your child has provided Us with Personal Data without
              your permission, please contact us. If We become aware that We
              have collected Personal Data from anyone under the age of 13
              without verification of parental consent, We take steps to remove
              that information from our servers.
            </p>
          </Element>
        </section>
        <section>
          <Element className={"block"} name="18">
            <h2 className="font-roboto mb-[1.25rem] font-semibold text-t18 lg:text-t24 text-black first-letter:capitalize">
              Changes To Our Privacy Policy
            </h2>

            <p className="text-t14 lg:text-[1rem] font-product_sans text-black/80 leading-[1.5rem]">
              If we decide to change our privacy policy, we will post those
              changes on this page, and/or update the Privacy Policy
              modification date below.
            </p>
          </Element>
        </section>
        <section>
          <Element className={"block"} name="19">
            <h2 className="font-roboto mb-[1.25rem] font-semibold text-t18 lg:text-t24 text-black first-letter:capitalize">
              Third-Party Services
            </h2>

            <div className="space-y-[1.5rem]">
              {[
                `We may display, Include or make available third-party content (including data, information, applications and other products services) or provide links to third- party websites or services ("Third- Party Services")                `,
                `You acknowledge and agree that we shall not be responsible for any Third party's accuracy, completeness, timeliness, validity, copyright compliance, legality, decency, quality or any other aspect thereafter. We do not assume and shall not have any liability or responsibility to you or any other person or entity for any Third-Party Services Third-Party Services and links thereto are provided solely as a convenience to you and you access and use them entirely at your own risk and subject to such third parties' terms and conditions.`,
              ].map((p, index) => (
                <p
                  key={index}
                  className="text-t14 lg:text-[1rem] font-product_sans text-black/80 leading-[1.5rem]"
                >
                  {p}
                </p>
              ))}
            </div>
          </Element>
        </section>
        <section>
          <Element className={"block"} name="20">
            <h2 className="font-roboto mb-[1.25rem] font-semibold text-t18 lg:text-t24 text-black first-letter:capitalize">
              Tracking Technologies
            </h2>

            <div className="space-y-[1.5rem]">
              {[
                `• Cookies: We use cookies to enhance the performance and functionality of our service but are non-essential to their use. However, without these cookies, certain functionality like videos may become unavailable or you would be required to enter your login details every time you visit our service as we would not be able to remember that you had logged in previously.`,
                `• Local Storage: Local Storage sometimes known 1 DOM storage provides weh apps with methods and protocols for storing client-side data. Web storage supports persistent data storage, similar to cookies but with a greatly enhanced capacity and no information stored in the HTTP request header.
                `,
              ].map((p, index) => (
                <p
                  key={index}
                  className="text-t14 lg:text-[1rem] font-product_sans text-black/80 leading-[1.5rem]"
                >
                  {p}
                </p>
              ))}
            </div>
          </Element>
        </section>
        <section>
          <Element className={"block"} name="21">
            <h2 className="font-roboto mb-[1.25rem] font-semibold text-t18 lg:text-t24 text-black first-letter:capitalize">
              Information about General Data Protection Regulation (GDPR)
            </h2>

            <p className="text-t14 lg:text-[1rem] font-product_sans text-black/80 leading-[1.5rem]">
              We may be collecting and using Information from you if you are
              (CEA), and in this section of our Privacy Policy we are going to
              explain exactly how and why is this data collected, and how we
              maintain this data under protection from being replicated or used
              in the wrong way.
            </p>
          </Element>
        </section>
        <section>
          <Element className={"block"} name="22">
            <h2 className="font-roboto mb-[1.25rem] font-semibold text-t18 lg:text-t24 text-black first-letter:capitalize">
              What is GDPR?
            </h2>

            <p className="text-t14 lg:text-[1rem] font-product_sans text-black/80 leading-[1.5rem]">
              GDPR is an EU-wide privacy and data protection law that regulates
              how EU residents&apos; data is protected by companies and enhances
              the control the EU residents have, over their personal data.
            </p>
          </Element>
        </section>
        <section>
          <Element className={"block"} name="23">
            <h2 className="font-roboto mb-[1.25rem] font-semibold text-t18 lg:text-t24 text-black first-letter:capitalize">
              What is personal data?
            </h2>

            <div className="space-y-[1.5rem]">
              {[
                `Any data that relates to an Identifiable or identified individual. GDPR covers a broad spectrum of Information that could be used on its own, or in combination with other pieces of information, to Identify a person. Personal data extends beyond a person's name or email address. Some examples Include financial Information, political opinions, genetic data, biometric data, IP addresses, orientation, and ethnicity. The Data Protection Principles include requirements such as:
                `,
                `• Personal data collected must be processed in a fair, legal, and transparent way and should only be used in a way that a person would reasonably expect. • Personal data should only be collected to fulfil a specific purpose and it should only be used for that purpose. Organizations must specify why they need the personal data when they collect it. Personal data should he held no longer than necessary to fulfil its purpose.`,
                `• People covered by the GDPR have the right to access their own personal data. They can also request a copy of their data, and that their data be updated, deleted, restricted, or moved to another organization`,
              ].map((p, index) => (
                <p
                  key={index}
                  className="text-t14 lg:text-[1rem] font-product_sans text-black/80 leading-[1.5rem]"
                >
                  {p}
                </p>
              ))}
            </div>
          </Element>
        </section>
        <section>
          <Element className={"block"} name="24">
            <h2 className="font-roboto mb-[1.25rem] font-semibold text-t18 lg:text-t24 text-black first-letter:capitalize">
              Why is GDPR important?
            </h2>

            <p className="text-t14 lg:text-[1rem] font-product_sans text-black/80 leading-[1.5rem]">
              GDPR adds some new requirements regarding how companies should
              protect Individuals&apos; personal data that they collect and
              process. It also raises the stakes for compliance by increasing
              enforcement and Imposing greater fines for breach. Beyond these
              facts it&apos;s simply the right thing to do. At Help Scout we
              strongly believe that your data privacy is very important and we
              already have solid security and privacy practices in place that go
              beyond the requirements of this new regulation.
            </p>
          </Element>
        </section>
        <section>
          <Element className={"block"} name="25">
            <h2 className="font-roboto mb-[1.25rem] font-semibold text-t18 lg:text-t24 text-black first-letter:capitalize">
              Individual Data
            </h2>

            <div className="space-y-[1.5rem]">
              {[
                `Subjects Rights - Data Access, Portability and Deletion `,
                `We are committed to helping our customers meet the data subject rights requirements of GDPR processes or stores all personal data in fully vetted, DPA compliant vendors. We do store all conversation and personal data for up to 6 years unless your account is deleted. In which case, we dispose of all data in accordance with our Terms of Service and Privacy Policy, but we will not hold it longer than 60 days
                `,
                `We are aware that if you are working with EU customers, you need to be able to provide them with the ability to access, update, retrieve and remove personal data. We got you! We've been set up as self service from the start and have always given you access to your data and your customers data. Our customer support team is here for you to answer any questions you might have about working with the API.`,
              ].map((p, index) => (
                <p
                  key={index}
                  className="text-t14 lg:text-[1rem] font-product_sans text-black/80 leading-[1.5rem]"
                >
                  {p}
                </p>
              ))}
            </div>
          </Element>
        </section>
        <section>
          <h2 className="font-roboto mb-[1.25rem] font-semibold text-t18 lg:text-t24 text-black first-letter:capitalize">
            Contact Us
          </h2>

          <div className="space-y-[1rem]">
            <p className="text-t14 lg:text-[1rem] font-product_sans text-black/80 leading-[1.5rem]">
              Don&apos;t hesitate to contact us if you have any questions.
            </p>
            <p className="text-t14 lg:text-[1rem] font-product_sans text-black/80 leading-[1.5rem]">
              <b>Email:</b>{" "}
              <a
                href="mailto:admin@niteon.co"
                className="text-blue-600 underline"
              >
                admin@niteon.co
              </a>
            </p>
            <p className="text-t14 lg:text-[1rem] font-product_sans text-black/80 leading-[1.5rem]">
              <b>Phone Number:</b>{" "}
              <a href="tel:+2348108035894" className="text-blue-600 underline">
                +2348108035894
              </a>
            </p>
            <p className="text-t14 lg:text-[1rem] font-product_sans text-black/80 leading-[1.5rem]">
              <b>Link:</b>{" "}
              <a
                href="https://www.niteon.co"
                className="text-blue-600 underline"
              >
                https://www.niteon.co
              </a>
            </p>
            <p className="text-t14 lg:text-[1rem] font-product_sans text-black/80 leading-[1.5rem]">
              <b>Address:</b> 1942 Broadway Ste 314C, Colorado, US
            </p>
          </div>
        </section>
      </GridLayout>
    </AppLayout>
  );
}

export default PrivacyPolicy;
